# Generated by Django 3.1.3 on 2021-01-07 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointed', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_title', models.CharField(max_length=200)),
                ('date_due', models.DateField()),
                ('time_due', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('choice1', models.CharField(default='', max_length=200)),
                ('choice2', models.CharField(default='', max_length=200)),
                ('choice3', models.CharField(default='', max_length=200)),
                ('choice4', models.CharField(default='', max_length=200)),
                ('answer', models.CharField(default='choice1', max_length=200)),
                ('assigned_mark', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_list', models.TextField(default='')),
                ('answer_list', models.TextField(default='')),
                ('user_answer', models.TextField(default='')),
                ('score_obtainable', models.IntegerField()),
                ('date_submitted', models.DateField()),
                ('time_submitted', models.TimeField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lms_app.assessment')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lms_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='lms_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='lms_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='lms_app.Enrollment', to='lms_app.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutors',
            field=models.ManyToManyField(through='lms_app.Appointment', to='lms_app.Tutor'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='courses',
            field=models.ManyToManyField(to='lms_app.Course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(to='lms_app.Question'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='lms_app.course'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tutors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='lms_app.tutor'),
        ),
    ]
