# Generated by Django 3.1.3 on 2021-01-16 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='sitting',
            name='score_obtainable',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_content',
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lms_app.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pass_mark',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='total_score',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lms_app.assessment'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tutor',
            name='registration_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default='choice1', max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_grade', models.PositiveBigIntegerField(default=0)),
                ('late_submission', models.PositiveSmallIntegerField(default=0)),
                ('failed', models.PositiveSmallIntegerField(default=0)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.sitting')),
            ],
        ),
    ]
