# Generated by Django 3.1.3 on 2021-01-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_auto_20210119_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='file_upload',
            field=models.FileField(upload_to='cv'),
        ),
    ]
