# Generated by Django 3.1.3 on 2021-01-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
