# Generated by Django 3.1.3 on 2021-01-19 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0008_apply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitting',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.student'),
        ),
    ]
