# Generated by Django 3.1.3 on 2021-01-19 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_auto_20210119_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitting',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.assessment'),
        ),
    ]
