# Generated by Django 3.1.3 on 2021-02-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0010_auto_20210119_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='course_slug',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='file_upload',
            field=models.FileField(default='', upload_to='courses/<django.db.models.fields.CharField>/display/'),
        ),
    ]
