# Generated by Django 3.1.3 on 2021-02-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0012_auto_20210202_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_prerequisite',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='file_upload',
            field=models.ImageField(default='', upload_to='courses/<django.db.models.fields.CharField>/display/'),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_header', models.CharField(max_length=500)),
                ('syllabus_body', models.TextField(max_length=2048)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_app.course')),
            ],
        ),
    ]
