# Generated by Django 3.1.3 on 2021-02-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0014_auto_20210203_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file_upload',
            field=models.FileField(default='', upload_to='courses/display/'),
        ),
    ]
