# Generated by Django 3.1.3 on 2021-02-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0015_auto_20210203_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='contents',
        ),
    ]
