# Generated by Django 3.1.3 on 2021-02-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0017_auto_20210211_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='question_content',
        ),
    ]
